### ISSUE TITLE
Production deployment documentation

### ISSUE THREAD

**Issue by jermdroui** [Conder-Systems/tuna-lang#44]
Provide documentation on how to deploy tuna code on to a cloud environment.

Provide examples for k8s.

**Comment by jermdroui** [comment]
@bryantc99 Please provide details on how you would like to deploy.

**Comment by bryantc99** [comment]
> To deploy a live webhook that can receive webhook events from the Messenger Platform, your code must be hosted on a public HTTPS server that meets the following requirements:
> 
> HTTPS support, Self-signed certificates are not supported
> A valid SSL certificate
> An open port that accepts GET and POST requests

[Link](https://developers.facebook.com/docs/messenger-platform/getting-started/webhook-setup/)
